#!/bin/bash
function help()
{
echo "**************** HELP INFO ***************"
echo "usage:"
echo "make [cmd] [opt=] ['exp'=]"
echo ""
echo "  [cmd]:"
echo "  help                  : default ,display option, how to use the script"
echo "  run                   : will run all include get_dutlist,gen_run,comp,sim"
echo "  get_flist              : get dut list"
echo "  gen_run               : generate run script command"
echo "  comp                  : compile"
echo "  sim                   : simulation"
echo "  ----opt=              : add self-define parameter when simulation,'--'as connector,become space character"
echo "  wave                  : wave view"
echo "  regr                  : regression testcase"
echo "  ----regr_tc=          : regression tc list which specify "
echo "  ----opt=              : add self-define parameter to all tc "
echo "                        : eg: 'opt=--+debug_en','--'as connector,add ' +debug_en' to all tc sim option"
echo "  report                : report all testcase html report"
echo "  cov                   : merge or view coverage info,default merge cov/*simv.vdb to gen report"
echo "  ----opt=              : merge directory 'xxx--yyy'('-dir xxx -dir yyy') to coverage db cov/merge_cov,'--'as connector"
echo "  ----report=           : view coverage report use 'dve' or 'web' browser "
echo "  clean                 : clean temp file"
echo "  ----opt=all           : delete whole sim proj workspace ${PROJ_WORK_PATH} "
echo "  ----opt=./            : delete temp in current directory "
echo "  tc                    : display 6_top/2_tc tc name ,for convenience to copy "
echo ""
echo "example:"
echo "  if want to display tc   , enter 'make tc' in terminal "
echo "  if want to run tc in TB , enter 'make run tc=tc_relu seed=123' in terminal "
echo "  if want to regress tc in TB , enter 'make regr' in terminal (use default proj=2_work , regr_tc=regr_tc) "
echo "  if want to regress tc in TB , enter 'make regr proj=sim_workspace regr_tc=my_regr_tc ' in terminal(specify regr_tc & sim_workspace) "
echo "  if want to remove whole sim file , enter 'make clean opt=all proj=test_proj' in terminal "
#env
}
help
